- name: instala e inicia apache
  hosts: nodes
  vars:
    http_port: 88
    max_clients: 222
  remote_user: bravo

  tasks:
  - name: install httpd
    yum: pkg=httpd state=latest
  - name: write apache config file
    template: src=/srv/httpd.j2 dest=/etc/httpd/conf/httpd.conf
  - name: start httpd
    service: name=httpd state=started
