- name: instala e inicia nginx
  hosts: nodes
  remote_user: bravo

  tasks:
  - name: add cache dir
    file:
        path: /opt/cache
        state: directory

  - name: install nginx
    yum:
        name: nginx
        state: latest
    notify: restart nginx

  handlers:
  - name: restart nginx
    service:
        name: nginx
        state: restarted
