---
- name: Setupe mariadb
  hosts: rh
  vars:
    database_packages:
      - mariadb-server
      - python3-PyMySQL

  tasks:
    - name: Install mariadb
      dnf:
        name: "{{ item }}"
        state: present
      loop: "{{ database_packages }}"
      when: ( ansible_facts.distribution == "RedHat" and  ansible_facts.distribution_major_version == "8" )

    - name: start the db service
      service:
        name: mariadb
        state: started
        enabled: true
      notify:
        - set db password

  handlers:
    - name: set db password
      mysql_user:
        name: root
        password: password
...
