---
- name: teste register
  hosts: all
  tasks:
    - name: show passwd
      shell: cat /etc/passwd
      register: passwd_contents
    - debug:
        # find_user defined in groups_var/all.yaml
        msg: echo "pass contains user {{ find_user }}"
      # In conditions, do not user {{ }}
      when: passwd_contents.stdout.find(find_user) != -1
...
