---
- name: show lists also known as arrays
  hosts: alma9
  # vars_files define files with variables definitions.
  vars_files:
    - vars/users-list.yaml
  tasks:
    - name: print array values
      debug:
        msg: "User {{ item.username }} has home {{ item.homedir }} and shell {{ item.shell }}"
      # users is an array var defined in vars/users-list.yaml
      loop: "{{ users }}"
    - name: print the second array value
      debug:
        msg: the second item is {{ users[1] }}
...
