---
- name: set selinux type on file
  hosts: all
  tasks:
    - name: install required packages
      dnf:
        name: policycoreutils-python-utils
        state: present
    - name: set selinux context
      sefcontext:
        target: /tmp/removeme
        setype: tmp_t
        state: present
      notify:
        - run restorecon
  handlers:
    - name: run restorecon
      command: restorecon -v /tmp/removeme
...
